# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a9212ad5d501328b2b60ee8916e63fbafc6bd7b0d2ba862d0fa3834652dcb24c99ecdc7c26bd852d857a6de545c3e463be2a28a778f3df3240ad34dd5378ed4

test:
  secret_key_base: 7f751a7347b3f80fd845789a77248d524a966c6aae3b8c0879993efb12e9ef9ac78ddbd576001aa65523b179cd860592e3faa01fefda796007b2705f44495647

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
